name: CI - separate results repo
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  rust-criterion-rs-framework:
    name: Run Criterion.rs benchmark example - github.com/benchmark-action/github-action-benchmark-results
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: rustup toolchain update nightly && rustup default nightly
      - name: Run benchmark
        run: cd examples/criterion-rs && cargo +nightly bench -- --output-format bencher | tee output.txt

      - uses: actions/checkout@v4
        with:
          repository: benchmark-action/github-action-benchmark-results
          ref: 'gh-pages'
          path: 'dist/other-repo'
      - name: Save previous data.js
        run: |
          cp ./dist/other-repo/dev/bench/data.js before_data.js

      - name: Store benchmark result
        uses: ./
        with:
          name: Criterion.rs Benchmark
          tool: 'cargo'
          output-file-path: examples/criterion-rs/output.txt
          fail-on-alert: true
          gh-repository: 'github.com/benchmark-action/github-action-benchmark-results'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: node ./dist/scripts/ci_validate_modification.js before_data.js 'Criterion.rs Benchmark' './benchmark-data-repository'
